## Prueba TODS

In [ ]:
import sys
sys.path.append("/mnt/homeGPU/mbautista/tods")
import argparse
import os
import numpy as np
import pandas as pd 
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
from sklearn import metrics
from d3m import index
from d3m.metadata.base import ArgumentType
from d3m.metadata.pipeline import Pipeline, PrimitiveStep
from axolotl.backend.simple import SimpleRunner
from tods import generate_dataset, generate_problem
from tods.searcher import BruteForceSearch
from tods import generate_dataset, load_pipeline, evaluate_pipeline
from tods.sk_interface.detection_algorithm.DeepLog_skinterface import DeepLogSKI
from tods.sk_interface.detection_algorithm.Telemanom_skinterface import TelemanomSKI

In [ ]:
data_UCR = np.loadtxt("../tods/src/tods/datasets/anomaly/raw_data/500_UCR_Anomaly_robotDOG1_10000_19280_19360.txt")

In [ ]:
print("shape:", data_UCR.shape)
print("datatype of data:",data_UCR.dtype)
print("First 5 rows:\n", data_UCR[:5])

X_train = np.expand_dims(data_UCR[:10000], axis=1)
X_test = np.expand_dims(data_UCR[10000:], axis=1)

In [ ]:
transformer = DeepLogSKI()
transformer.fit(X_train)
prediction_labels_train = transformer.predict(X_train)
prediction_labels_test = transformer.predict(X_test)
prediction_score = transformer.predict_score(X_test)

In [ ]:
transformer = TelemanomSKI(l_s= 2, n_predictions= 1)
transformer.fit(X_train)
prediction_labels_train = transformer.predict(X_train)
prediction_labels_test = transformer.predict(X_test)
prediction_score = transformer.predict_score(X_test)

## S-ADL + TODS Prueba

In [5]:
import sys
sys.path.append("/mnt/homeGPU/mbautista/tods")
sys.path.append("/mnt/homeGPU/mbautista/S-ADL")
from tods.detection_algorithm.DeepLog import DeepLogPrimitive
    
from inspect import signature

from SADL.time_series.algorithms import tods
from tods.sk_interface.detection_algorithm.DeepLog_skinterface import DeepLogSKI

transformer = DeepLogSKI()

In [ ]:
#init_signature = signature(algorithm_.__init__)
init_signature = DeepLogSKI()
signature(DeepLogSKI().__base__.__name__)

In [ ]:
from tods.detection_algorithm import UODBasePrimitive
deeplog_ski = DeepLogSKI()
deeplog_primitive = DeepLogPrimitive()
#print(deeplog_ski.primitives[0])

#print(deeplog_ski.__class__.__base__)
#print(DeepLogPrimitive.metadata.get_hyperparams().defaults().keys())

#for sys_idx, primitive in enumerate(deeplog_ski.primitives):
    #print(primitive.)
init_signatures = signature(deeplog_ski.__class__.__base__)
#print(init_signatures.parameters["primitive"])
#deeplog_ski.primitive.__name__

#for param_name, param in init_signatures.parameters.items():
#    print(param)


for sys_idx, primitive in enumerate(deeplog_ski.primitives):
    print(primitive)
   #primitive.fit()

#print(deeplog_ski.__class__.__base__)
#print(deeplog_ski.primitives[0])
print(DeepLogPrimitive.metadata.get_hyperparams().defaults().keys())
print(DeepLogPrimitive.__base__.__name__)
print(DeepLogPrimitive.__base__)
print(UODBasePrimitive.UnsupervisedOutlierDetectorBase)
init_signatures = signature(DeepLogPrimitive.__base__.__init__)
for param_name, param in init_signatures.parameters.items():
    print(param)
print(init_signatures.parameters.items()["hyperparams"])
#print(DeepLogPrimitive.__base__.metadata.get_hyperparams().defaults().keys())

In [1]:
from tods.sk_interface.detection_algorithm.Telemanom_skinterface import TelemanomSKI
from tods.detection_algorithm import UODBasePrimitive
from SADL.time_series.algorithms.tods import TodsAnomalyDetection

telemanom = TelemanomSKI(patience=20)
#telemanom.primitives

kwargs = {"algorithm_": "telemanon", "label_parser": None, "l_s":  2, "n_predictions": 1}
telemanon_mio = TodsAnomalyDetection(**kwargs)

print(telemanon_mio.get_params())

#kwargs = {"algorithm_": "telemanon", "label_parser": False, "patience": 10000, "use_semantic_types": True, "l_s": 5}
#telemanon_mio.set_params(**kwargs)


#print(telemanon_mio.get_params())

2024-03-14 08:37:48.671008: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0


{'label_parser': None, 'algorithm_': 'TelemanomSKI', 'primitive_params_': Hyperparams({'contamination': 0.1, 'window_size': 10, 'step_size': 1, 'return_subseq_inds': False, 'use_columns': (), 'exclude_columns': (), 'return_result': 'new', 'use_semantic_types': False, 'add_index_columns': False, 'error_on_no_input': True, 'return_semantic_type': 'https://metadata.datadrivendiscovery.org/types/Attribute', 'smoothing_perc': 0.05, 'window_size_': 100, 'error_buffer': 50, 'batch_size': 70, 'dropout': 0.3, 'validation_split': 0.2, 'optimizer': 'Adam', 'lstm_batch_size': 64, 'loss_metric': 'mean_squared_error', 'layers': [10, 10], 'epochs': 1, 'patience': 10, 'min_delta': 0.0003, 'l_s': 2, 'n_predictions': 1, 'p': 0.05})}


In [4]:
import numpy as np
data_UCR = np.loadtxt("SADL/time_series/algorithms/500_UCR_Anomaly_robotDOG1_10000_19280_19360.txt")
print("shape:", data_UCR.shape)
print("datatype of data:",data_UCR.dtype)
print("First 5 rows:\n", data_UCR[:5])
X_train = np.expand_dims(data_UCR[:10000], axis=1)
X_test = np.expand_dims(data_UCR[10000:], axis=1)
print("First 5 rows train:\n", X_train[:5])
print("First 5 rows test:\n", X_test[:5])

shape: (40000,)
datatype of data: float64
First 5 rows:
 [0.145299 0.128205 0.094017 0.076923 0.111111]
First 5 rows train:
 [[0.145299]
 [0.128205]
 [0.094017]
 [0.076923]
 [0.111111]]
First 5 rows test:
 [[0.076923]
 [0.076923]
 [0.076923]
 [0.094017]
 [0.145299]]


In [3]:
#telemanon_mio.fit(X_train)

2024-03-13 11:30:38.970905: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2024-03-13 11:30:38.971159: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2024-03-13 11:30:38.974481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:8a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-03-13 11:30:38.974548: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2024-03-13 11:30:38.981480: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2024-03-13 11:30:38.981575: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2

125/125 [==============================] - 6s 12ms/step - loss: 0.0200 - val_loss: 0.0052


In [4]:
prediction_labels_train = telemanon_mio.predict(X_train)
prediction_labels_test = telemanon_mio.predict(X_test)
prediction_raw = telemanon_mio.decision_function(X_test)

print("Prediction Labels\n", prediction_labels_test)
print("Prediction Raw\n", prediction_raw)

TODSError decision_function(): 'TelemanomSKI' object has no attribute 'clf_'
For further reference please see: https://tods-doc.github.io/index.html
Prediction Labels
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Prediction Raw
 None


In [2]:
kwargs = {"algorithm_": "deep_log", "label_parser": None, "features": 7}
deep_log_mio = TodsAnomalyDetection(**kwargs)

print(deep_log_mio.get_params())

{'label_parser': None, 'algorithm_': 'DeepLogSKI', 'primitive_params_': Hyperparams({'contamination': 0.1, 'window_size': 1, 'step_size': 1, 'return_subseq_inds': False, 'use_columns': (), 'exclude_columns': (), 'return_result': 'new', 'use_semantic_types': False, 'add_index_columns': False, 'error_on_no_input': True, 'return_semantic_type': 'https://metadata.datadrivendiscovery.org/types/Attribute', 'hidden_size': 64, 'loss': 'mean_squared_error', 'optimizer': 'Adam', 'epochs': 10, 'batch_size': 32, 'dropout_rate': 0.2, 'l2_regularizer': 0.1, 'validation_size': 0.1, 'features': 7, 'stacked_layers': 1, 'preprocessing': True, 'verbose': 1})}


In [5]:
deep_log_mio.fit(X_train)

2024-03-14 08:50:25.268490: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2024-03-14 08:50:25.268792: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2024-03-14 08:50:25.269716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:8a:00.0 name: Tesla V100-SXM2-32GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 31.74GiB deviceMemoryBandwidth: 836.37GiB/s
2024-03-14 08:50:25.269774: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2024-03-14 08:50:25.276351: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2024-03-14 08:50:25.276440: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2

Epoch 1/10


2024-03-14 08:50:29.367477: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2024-03-14 08:50:29.879821: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2024-03-14 08:50:29.904148: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8


282/282 [==============================] - 6s 6ms/step - loss: 0.5856 - val_loss: 0.2637
Epoch 2/10
282/282 [==============================] - 1s 3ms/step - loss: 0.3435 - val_loss: 0.2575
Epoch 3/10
282/282 [==============================] - 1s 3ms/step - loss: 0.3466 - val_loss: 0.2716
Epoch 4/10
282/282 [==============================] - 1s 3ms/step - loss: 0.3474 - val_loss: 0.2647
Epoch 5/10
282/282 [==============================] - 1s 3ms/step - loss: 0.3454 - val_loss: 0.2703
Epoch 6/10
282/282 [==============================] - 1s 4ms/step - loss: 0.3543 - val_loss: 0.2423
Epoch 7/10
282/282 [==============================] - 1s 3ms/step - loss: 0.3543 - val_loss: 0.2587
Epoch 8/10
282/282 [==============================] - 1s 3ms/step - loss: 0.3364 - val_loss: 0.2806
Epoch 9/10
282/282 [==============================] - 1s 3ms/step - loss: 0.3424 - val_loss: 0.2899
Epoch 10/10
282/282 [==============================] - 1s 3ms/step - loss: 0.3326 - val_loss: 0.2846


In [1]:
from pyod.utils.data import generate_data
from SADL.time_series.algorithms.tods import TodsAnomalyDetection
from sklearn.metrics import roc_auc_score

maxDiff = None
n_train = 200
n_test = 100
contamination = 0.1
roc_floor = 0.0
window_size = 5
l_s = 5
n_predictions = 1


X_train, X_test,y_train,  y_test = generate_data(
    n_train=n_train, n_test=n_test, n_features=3,
    contamination=contamination, random_state=42)

kwargs = {"label_parser": None, "algorithm_": "telemanom", "contamination": contamination,
            "l_s": l_s, "n_predictions": n_predictions}

transformer = TodsAnomalyDetection(**kwargs)

2024-03-14 10:50:38.589636: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0


In [4]:
y_train = y_train[l_s:-n_predictions]
y_test = y_test[l_s:-n_predictions]
transformer.fit(X_train)
pred_labels = transformer.predict(X_test)
print(pred_labels.shape[0], y_test.shape[0])
pred_scores = transformer.model.predict_score(X_test)
print(pred_scores.shape[0], y_test.shape[0])

3/3 [==============================] - 3s 299ms/step - loss: 38.4516 - val_loss: 26.5037
94 82
94 82


In [7]:
from SADL.time_series.algorithms.tods import TodsAnomalyDetection

kwargs = {"label_parser": None, "algorithm_": "system_wise", "contamination": 0.1}

transformer = TodsAnomalyDetection(**kwargs)
transformer.get_params()

{'label_parser': None,
 'algorithm_': 'SODSKI',
 'primitive_params_': Hyperparams({'contamination': 0.1, 'window_size': 10, 'step_size': 1, 'return_subseq_inds': False, 'use_columns': (), 'exclude_columns': (), 'return_result': 'new', 'use_semantic_types': False, 'add_index_columns': False, 'error_on_no_input': True, 'return_semantic_type': 'https://metadata.datadrivendiscovery.org/types/Attribute', 'n_neighbors': 20, 'ref_set': 10, 'alpha': 0.8})}

In [4]:
from pyod.utils.data import generate_data
from SADL.time_series.algorithms.tods import TodsAnomalyDetection
from sklearn.metrics import roc_auc_score

maxDiff = None
n_train = 200
n_test = 100
contamination = 0.1
roc_floor = 0.0
window_size = 5
l_s = 5
n_predictions = 1


X_train, X_test,y_train,  y_test = generate_data(
    n_train=n_train, n_test=n_test, n_features=3,
    contamination=0.1, random_state=42)

In [5]:
transformer.fit(X_train)

TODSError fit(): set_training_data() got an unexpected keyword argument 'inputs'
For further reference please see: https://tods-doc.github.io/index.html
